### ISSUE TITLE
Creating an EC2 AMI

### ISSUE THREAD

**Issue by patrickbcullen** [coreos/manifest#53]
I have followed the steps for building a CoreOS from source on https://coreos.com/docs/sdk-distributors/sdk/modifying-coreos/. At the end of the build I created an AMI image using
```shell
./image_to_vm.sh --from=../build/images/amd64-usr/developer-509.0.0+2014-11-24-1918-a1 --board=amd64-usr --format ami
```

It is not clear how to create an EBS backed AMI using this binary. Can you provide any more details on how the automated AMI build process works for CoreOS?

**Comment by pwaller** [comment]
See also https://github.com/coreos/bugs/issues/177

/cc @wmark who seems to know how to achieve it.

**Comment by wmark** [comment]
1. Grab an existing image.
 2. Extract it to a 10G loop device.
 3. Modify it. (Mount the partitions as usual.)
 4. Package it up using Amazon's tools, selecting "instance store" as storage. Upload, done.

Your first iteration could be without step 3 and result in an AMI that starts.

Your second iteration should:
 * Incorporate files you can find here: https://github.com/coreos/coreos-overlay/tree/master/coreos-base/oem-ec2-compat/files (if you didn't use the *coreos_production_ami_hvm…* image in the first place)…
 * … and add ```reboot-stategy: none``` because that wouldn't work with instance-backed machines
 * … as well as disable *locksmith*. Don't disable the *updater-service*, because you could still need it for reporting.
 * Optionally format, and mount /dev/xvda (xvdb, xvdc…), for example to ```/var/lib/docker``` and ```/var/lib/docker/volumes```.

Your third iteration could:
 * Use *Ceph*, or any other distributed storage, for Docker images.
 * ```touch .noupdate``` on partition ```ROOT-B```.

**Comment by pwaller** [comment]
> … and add reboot-stategy: none because that wouldn't work with instance-backed machines

Are you sure you can't reboot instance store machines? I thought it was just that you couldn't turn them off and back on.

**Comment by wmark** [comment]
> Are you sure you can't reboot instance store machines?
> I thought it was just that you couldn't turn them off and back on.

You're right, my mistake. There's different reason not to use restarts, but, true, you could skip steps.
